# Model Hyper Parameters
SEQ_LEN =  20
CLASS_NUM = 128 + 1
CHORD_CLASS_NUM = 84
FRAME_PER_SECOND = 3

# Training Parameters
EPOCHS = 1000
BATCH_SONG_SIZE =16 
BATCH_SIZE = 256
VALIDATION_INTERVAL = 1

SUMMARY_INTERVAL = 10
VALIDATION_INTERVAL = 10

# Environment
DATA_DIR = 'dataset_debug'
SAVE_DIR = 'save'
LOG_DIR = 'log'
